export const JOB_LIST_REQUEST = 'JOB_LIST_REQUEST ';
export const JOB_MEMBER_REQUEST = 'JOB_MEMBER_REQUEST';
export const JOB_LIST_LOADING = 'JOB_LIST_LOADING';
export const JOB_LIST_SUCCESS = 'JOB_LIST_SUCCESS';
export const JOB_LIST_ERROR = 'JOB_LIST_ERROR';
export const JOB_LIST_ERRORS = 'JOB_LIST_ERRORS';
