export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST ';
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const USER_PROFILE_ERRORS = 'USER_PROFILE_ERRORS';
