export const HIRE_USER_REQUEST = 'HIRE_USER_REQUEST ';
export const HIRE_USER_LOADING = 'HIRE_USER_LOADING';
export const HIRE_USER_SUCCESS = 'HIRE_USER_SUCCESS';
export const HIRE_USER_ERROR = 'HIRE_USER_ERROR';
export const HIRE_USER_ERRORS = 'HIRE_USER_ERRORS';
