export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST ';
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_ERRORS = 'LOGIN_USER_ERRORS';
export const OPEN_USER_DRAWER = 'OPEN_USER_DRAWER';
