export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST ';
export const SIGNUP_USER_LOADING = 'SIGNUP_USER_LOADING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';
export const SIGNUP_USER_ERRORS = 'SIGNUP_USER_ERRORS';
